### ISSUE TITLE
Integrating other repos with hugo

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io#539]
The website relies heavily on integrating content from other repos, such as bindings, adapters, and tutorials.

We need to figure how to achieve this in hugo.
The way to go seems to be using module mounts: https://gohugo.io/configuration/module/#mounts

**Comment by fsimonis** [comment]
The following mount points mount the majority of the content.

Current issues:
* there are non-website documentation pages
* a group of pages that should appear as a section on the website still need some `_index.md` to mark it as a section. This either needs to be provided in the adapters or in the website repo.

```yaml
    # Tooling
  - source: imported/aste/docs
    target: content/docs/tooling
    excludeFiles: CONTRIBUTING.md
    # Adapters
  - source: imported/dumux-adapter/docs
    target: content/docs/adapters/dumux-adapter
  - source: imported/dune-adapter/docs
    target: content/docs/adapters/dune-adapter
  - source: imported/fmi-runner/docs
    target: content/docs/adapters/fmi-runner
  - source: imported/micro-manager/docs
    target: content/docs/adapters/micro-manager
    excludeFiles: ReleaseGuide.md
  - source: imported/openfoam-adapter/docs
    target: content/docs/adapters/openfoam-adapter
  - source: imported/preeco-orga/docs
    target: content/docs/adapters/preeco-orga
  - source: imported/su2-adapter/docs
    target: content/docs/adapters/su2-adapter
    # Tutorials
  - source: imported/tutorials
    target: content/tutorials
    includeFiles: /*/{README.md,images/*}
```
